TPreloadTexture(path="Resources/Images/Characters/charTorsoAnimated.png", name="charTorsoAnimated")
TPreloadTexture(path="Resources/Images/Characters/charLegsAnimated.png", name="charLegsAnimated")
TPreloadTexture(path="Resources/Images/Characters/charWeaponHold.png", name="charWeaponHold")
TPreloadTexture(path="Resources/Images/Characters/charTorso.png", name="charTorso")

TPreloadTexture(path="Resources/Images/Weapons/rocketLauncher.png", name="rocketLauncher")
TPreloadTexture(path="Resources/Images/Weapons/splode.png", name="splode")
TPreloadTexture(path="Resources/Images/Weapons/pistol.png", name="pistol")
TPreloadTexture(path="Resources/Images/Weapons/rocket.png", name="rocket")
TPreloadTexture(path="Resources/Images/Weapons/rifle.png", name="rifle")

TPreloadTexture(path="Resources/Images/nextLevelPad.png", name="nextLevelPad")
TPreloadTexture(path="Resources/Images/deadPlayer.png", name="deadPlayer")
TPreloadTexture(path="Resources/Images/health.png", name="health")
TPreloadTexture(path="Resources/Images/deadAi.png", name="deadAi")
TPreloadTexture(path="Resources/Images/ammo.png", name="ammo")

TPreloadTexture(path="Resources/Images/Boss/bossMain.png", name="bossMain")
TPreloadTexture(path="Resources/Images/Boss/bossArm.png", name="bossArm")

TPreloadTexture(path="Resources/Scenes/Scene_1/scene.png", name="scene_1")
TPreloadTexture(path="Resources/Scenes/Scene_2/scene.png", name="scene_2")
TPreloadTexture(path="Resources/Scenes/Scene_3/scene.png", name="scene_3")
TPreloadTexture(path="Resources/Scenes/Scene_4/scene.png", name="scene_4")
TPreloadTexture(path="Resources/Scenes/Scene_5/scene.png", name="scene_5")

TPreloadTextRenderer(path="Resources/Fonts/munro.ttf", name="munroDebug", color="2", alpha="0.5")
TPreloadTextRenderer(path="Resources/Fonts/munro.ttf", name="munro", color="0", alpha="1.0")

TPreloadSoundStream(path="Resources/Audio/music1.wav", name="game_music_1")
TPreloadSoundStream(path="Resources/Audio/music.wav", name="menu_music")

TPreloadSoundEffect(path="Resources/Audio/shot_muffled.wav", name="shot_muffled")
TPreloadSoundEffect(path="Resources/Audio/shell_basic.wav", name="shell_basic")
TPreloadSoundEffect(path="Resources/Audio/shot_basic.wav", name="shot_basic")
TPreloadSoundEffect(path="Resources/Audio/explosion.wav", name="explosion")
TPreloadSoundEffect(path="Resources/Audio/shotgun.wav", name="shotgun")
TPreloadSoundEffect(path="Resources/Audio/money.wav", name="money")
TPreloadSoundEffect(path="Resources/Audio/cock.wav", name="cock")
TPreloadSoundEffect(path="Resources/Audio/drop.wav", name="drop")

TName(name="Isabelle")
TName(name="Matthieu")
TName(name="Marleen")
TName(name="Andries")
TName(name="Goedele")
TName(name="Fabeeto")
TName(name="Mathias")
TName(name="Istvan")
TName(name="Houari")
TName(name="Daniel")
TName(name="Yosha")
TName(name="Joost")
TName(name="Thijs")
TName(name="Ruben")
TName(name="Robin")
TName(name="Tomas")
TName(name="Timo")
TName(name="Bart")
TName(name="Jeff")
TName(name="Luna")
TName(name="Elon")
TName(name="Rik")
TName(name="Ivo")
TName(name="Tom")
TName(name="Pao")