TPreloadTexture(path="Resources/Images/Characters/charTorso.png", name="charTorso")
TPreloadTexture(path="Resources/Images/Characters/charLegsAnimated.png", name="charLegsAnimated")
TPreloadTexture(path="Resources/Images/Characters/charTorsoAnimated.png", name="charTorsoAnimated")
TPreloadTexture(path="Resources/Images/Characters/charWeaponHold.png", name="charWeaponHold")
TPreloadTexture(path="Resources/Images/Weapons/rifle.png", name="rifle")
TPreloadTexture(path="Resources/Images/Weapons/pistol.png", name="pistol")
TPreloadTexture(path="Resources/Images/Weapons/rocket.png", name="rocket")
TPreloadTexture(path="Resources/Images/Weapons/rocketLauncher.png", name="rocketLauncher")
TPreloadTexture(path="Resources/Images/Weapons/splode.png", name="splode")
TPreloadTexture(path="Resources/Images/nextLevelPad.png", name="nextLevelPad")
TPreloadTexture(path="Resources/Images/health.png", name="health")

TPreloadTexture(path="Resources/Images/deadAi.png", name="deadAi")
TPreloadTexture(path="Resources/Images/deadPlayer.png", name="deadPlayer")

TPreloadTexture(path="Resources/Scenes/Scene_1/scene.png", name="scene_1")
TPreloadTexture(path="Resources/Scenes/Scene_2/scene.png", name="scene_2")

TPreloadTextRenderer(path="Resources/Fonts/munro.ttf", name="munro")

TPreloadSoundStream(path="Resources/Audio/music.wav", name="menu_music")
TPreloadSoundStream(path="Resources/Audio/music1.wav", name="game_music_1")

TPreloadSoundEffect(path="Resources/Audio/cock.wav", name="cock")
TPreloadSoundEffect(path="Resources/Audio/drop.wav", name="drop")
TPreloadSoundEffect(path="Resources/Audio/money.wav", name="money")
TPreloadSoundEffect(path="Resources/Audio/shell_basic.wav", name="shell_basic")
TPreloadSoundEffect(path="Resources/Audio/shot_basic.wav", name="shot_basic")
TPreloadSoundEffect(path="Resources/Audio/shot_muffled.wav", name="shot_muffled")
TPreloadSoundEffect(path="Resources/Audio/shotgun.wav", name="shotgun")
TPreloadSoundEffect(path="Resources/Audio/explosion.wav", name="explosion")